params:
  title: "Daniel Mesquita's Portfolio"
  description: Software Engineer (Full-stack developer) specialized in Go (Golang), Python, Node.js, Typescript, Javascript, React & React Native
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    # textColor:
    # secondaryTextColor:
    # backgroundColor:
    # secondaryBackgroundColor:
    # primaryColor:
    # secondaryColor:

    darkmode:
      textColor: "#f1f2f5"
      secondaryTextColor: "#b0b3b8"
      backgroundColor: "#18191a"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#33a2ff"
      secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Daniel Mesquita" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Daniel Mesquita."
    subtitle: "Software Engineer"
    content: "I help companies build high-quality, performant, user-friendly applications that exceed their business objectives."
    image: /images/hero.png
    bottomImage:
      enable: true
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://raw.githubusercontent.com/danielmesquitta/danielmesquitta/main/docs/Daniel%20Mesquita%20-%20Resume.pdf"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/danielmesquitta
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/danielmesquitta/

  # About
  about:
    enable: true
    title: "About Me"
    # image: "/images/me.png"
    content: |
      I am a Developer with 4 years of work experience dedicated to build software that exceed expectations.
      <br/><br/>

    skills:
      enable: true
      title: |
        Here are a few technologies I've been working with through my career:
      items:
        - "Go (Golang)"
        - "Python"
        - "Node"
        - "Typescript & Javascript"
        - "SQL & NoSQL"
        - "AWS & GCP"
        - "React / React Native"
        - "Next.js"
        - "Unit / integration / e2e testing"
        - "Git & Version control"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Full-stack Software Developer"
        company: "Moss Earth"
        companyUrl: "https://moss.earth/"
        date: "Sep 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          I am currently working as a software developer at Moss Earth. I have concentrated on enhancing and developing systems and microservices to support our mission of leveraging technology for environmental conservation.

          My contributions have been crucial in improving the efficiency of APIs for processing millions of daily requests, automating processes with external APIs from Pipefy, HubSpot, Slack, and Google Docs, significantly reducing weekly work hours in other departments, and promoting a more efficient systems and work environment.

          <br/>
          <div class="container">
            <div class="row align-items-center">
              <div class="col">
                <img src="/images/experience/moss-1.webp" width="100%" />
              </div>
              <div class="col">
                <img src="/images/experience/moss-2.webp" width="100%" />
              </div>
            </div>
            <div class="row align-items-center">
              <div class="col">
                <img src="/images/experience/moss-3.webp" width="100%" />
              </div>
              <div class="col">
                <img src="/images/experience/moss-4.webp" width="100%" />
              </div>
            </div>
            <div class="row align-items-center">
              <div class="col">
                <img src="/images/experience/moss-5.webp" width="100%" />
              </div>
              <div class="col">
                <img src="/images/experience/moss-7.webp" width="100%" />
              </div>
            </div>
          </div>

      - job: "Full-stack Software Developer"
        company: "Flow lab"
        companyUrl: "https://www.flowlabdigital.com.br/"
        date: "Oct 2020 - Sep 2023"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Flow Lab is a digital agency that develops custom software for companies in various industries. I was responsible for developing and maintaining systems for clients in the healthcare, agriculture, and civil construction sectors.

          Some examples of my work include:

          🏗️ <b>BOMDIA</b>

          I was the Lead Back-End Developer at BomDia. Our solution transcends traditional, paper-based methods by providing a modern, digital alternative. The platform includes user and project management, financial control, a mobile app for check-ins and check-outs, report generation and much more.

          <br/>
          <div class="container">
            <div class="row align-items-center">
              <div class="col">
                <img width="100%" src="/images/experience/bomdia-1.webp" />
              </div>
              <div class="col">
                <img src="/images/experience/bomdia-2.webp" width="100%" />
              </div>
            </div>
            <div class="row align-items-center">
              <div class="col">
                <div class="container">
                  <div class="row align-items-center">
                    <div class="col">
                      <img src="/images/experience/bomdia-5.webp" width="100%" />
                    </div>
                    <div class="col">
                      <img src="/images/experience/bomdia-6.webp" width="100%" />
                    </div>
                  </div>
                </div>
              </div>
              <div class="col">
                <img src="/images/experience/bomdia-3.webp" width="100%" />
              </div>
            </div>
          </div>
          <br/>

          🩺 <b>MEDFY</b>

          MEDFY is a system that allows attendants in the <a href="https://www.umcenter.com.br/" target="__blank">UMC hospital</a> locate available doctors through specialties, clinics, and compatible health insurance options.

          <br/>
          <div class="container">
            <div class="row align-items-center">
              <div class="col">
                <img width="100%" src="/images/experience/umc-system.webp" />
              </div>
              <div class="col">
                <img width="100%" src="/images/experience/umc-system-2.webp" />
              </div>
            </div>
          </div>
          <br/>

          🌿 <b>EVEREST</b>

          Using our expertise in development, we've created a system that generates reports that shows the nutritional balance of each nutrient and gives actionable steps for optimizing plant productivity.

          <br/>
          <div class="container">
            <div class="row align-items-center">
              <div class="col">
                <img src="/images/experience/everest-3.webp" width="100%" />
              </div>
              <div class="col">
                <img src="/images/experience/everest-1.webp" width="100%" />
              </div>
            </div>
          </div>

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of System Analysis and Development"
        school:
          name: "University Estácio de Sá, Uberlândia - MG, Brazil"
          url: "https://estacio.br/a-estacio/sobre-a-estacio"
        date: "2021 - 2025"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: English Course
        content: I've finished the Park Education English course and have become fluent.
        url: https://park.education/sobre-nos/
        image: /images/achievment.jpg

  # Projects
  projects:
    enable: true
    title: "Popular Posts"
    items:
      - title: "Project Ideas: Go Programming Language"
        content: Are you a Go enthusiast looking for your next coding adventure? Look no further! Here are some intriguing Golang project ideas to sharpen your skills and make an impact on the next person who looks at your portfolio.
        image: /images/posts/project-ideas.png
        featured:
          name: See more
          link: https://www.linkedin.com/feed/update/urn:li:activity:7112752743693324289/
        badges:
          - "Go"
          - "Back-end"

      - title: Goroutines Management with Go Context
        content: Context is a powerful tool in the Go programming language, helping you manage concurrency, timeouts, and cancellation effectively. It's crucial for building robust and efficient applications.
        image: /images/posts/goroutines.png
        featured:
          name: See more
          link: https://www.linkedin.com/feed/update/urn:li:activity:7110578415270793217/
        badges:
          - "Go"
          - "Back-end"
          - "Concurrency"

      - title: Don't use ORM's with Go, do this instead
        content: ORMs can sometimes introduce unnecessary complexity and performance bottlenecks. But there is a solution! SQLC lets you write SQL queries in .sql files, converting it to Go code, keeping things native, efficient and safe.
        image: /images/posts/orms.png
        featured:
          name: See more
          link: https://www.linkedin.com/feed/update/urn:li:activity:7099344430125494272/
        badges:
          - "Go"
          - "Back-end"
          - "SQL"
          - "ORM"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:danielmesquitta123@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/danielmesquitta
      linkedin: https://linkedin.com/in/danielmesquitta

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
